#!/bin/bash
# Diego García Gonzalez (diegargon) diego@envigo.net
# v1.0
### BEGIN INIT INFO
# Provides: domo
# Required-Start: 
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start and Stop
# Description:
### END INIT INFO

DOMO_PATH=/usr/local/sbin/domo

do_start() {

}

do_start() {

}

case "$1" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
                do_start
                ;;
        status)
                exit 0
                ;;
        *)
                echo "Usage: /etc/init.d/domo  {start|stop|restart} "
                ;;
esac
